### ISSUE TITLE
Merge flake8 configurations

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1053]
Currently we have `tox.ini` with only flake8-related configuration and `.flake8`.
In the workflow of torchaudio development we do not use `tox`.
I do not know the origin of them but we should merge these into `.flake8`.
PyTorch repo does not have `tox.ini` either so it's simpler for us to do the same thing.

**Comment by bhargavkathivarapu** [comment]
@mthrok  Along with flake8 configurations can we include precommit hooks , so that style issues , imports ordering ,unused imports etc  won't come into commits. It seems Pytorch already has  a pre commit setup( https://github.com/pytorch/pytorch/blob/master/tools/git-pre-commit ) . May be we can extended that for this repo or use configuarations like [isort](https://github.com/PyCQA/isort) , [pre-commit](https://pre-commit.com/) along with flake8

**Comment by mthrok** [comment]
@bhargavkathivarapu 

Thanks for the suggestion. However, in my experience, this kind of pre-commit hook is more counter-productive than helpful. I often push my WIP branch for the purpose of backup, because my development workflow sometimes involve multiple machines on network. I polish my changes only before publishing a PR and pre-commit hook only helps in those occasions.

Also one has to install pre-commit hook manually, so there is no automatic enforcement.

**Comment by krishnakalyan3** [comment]
@mthrok, I would like to take a stab at this. 

From what I understand 
https://github.com/pytorch/audio/blob/master/.flake8
https://github.com/pytorch/audio/blob/master/tox.ini

should be merged to `.flake8` and `tox.ini` removed. Is this understanding correct?.
Is there a way to test this locally in my system?.
