### ISSUE TITLE
inconsistent parameter name in `load` for different backends

### ISSUE THREAD

**Issue by csukuangfj** [pytorch/audio#1102]
`normalize` vs `normalization`.

It makes it difficult to switch to different backends because of the different parameter name.

See the code below.

## no_backend

https://github.com/pytorch/audio/blob/80c97e6a78b6f1ead85d04c40badaa1014d8a24d/torchaudio/backend/no_backend.py#L13

## soundfile

https://github.com/pytorch/audio/blob/80c97e6a78b6f1ead85d04c40badaa1014d8a24d/torchaudio/backend/soundfile_backend.py#L31

## sox

https://github.com/pytorch/audio/blob/80c97e6a78b6f1ead85d04c40badaa1014d8a24d/torchaudio/backend/sox_backend.py#L22

## sox_io

https://github.com/pytorch/audio/blob/80c97e6a78b6f1ead85d04c40badaa1014d8a24d/torchaudio/backend/sox_io_backend.py#L34

**Comment by csukuangfj** [comment]
BTW: some parameters are even missing in ``load`` within ``sox_io``. E.g., the ``out`` parameter.

I was expecting that ``load`` in all backends has the same interface.

**Comment by csukuangfj** [comment]
Furthermore, the value ``0`` of the parameter ``num_frames``in ``load`` has a **different** meaning in different backends.

**Comment by mthrok** [comment]
Hi @csukuangfj 

Please refer to the documentation and #903 for the migration guide. We are intentionally introducing the BC breaking changes to achieve consistent behavior and interface across backends.

"sox" and "soundfile (legacy interface)" are the ones deprecated and "sox_io" and "soundfile (new interface)" are the replacement for the deprecated ones. "no_backend" is not intended for external use thus undocumented. It purpose is to fill the void therefore it should just match the interface of default backends.

* `out` parameter is removed because there is no technical advantage etc.
* `normalization` in the deprecated backends allowed arbitrary transformation, which is not normalization. Therefore it's been removed.

> Furthermore, the value `0` of the parameter `num_frames`in `load` has a **different** meaning in different backends.

Can you elaborate?

**Comment by csukuangfj** [comment]
@mthrok 
Thanks for pointing to the link. I will read it.

---

> Can you elaborate?


In `soundfile_backend.py`, `num_frames == 0` is equivalent to `num_frames == -1`:
https://github.com/pytorch/audio/blob/80c97e6a78b6f1ead85d04c40badaa1014d8a24d/torchaudio/backend/soundfile_backend.py#L54-L55

However, in `sox_io` backend, it is a runtime error to set `num_frames` to 0. See the code

https://github.com/pytorch/audio/blob/80c97e6a78b6f1ead85d04c40badaa1014d8a24d/torchaudio/csrc/sox_io.cpp#L62-L65

**Comment by mthrok** [comment]
@csukuangfj 

The `soundfile_backend.py` belongs to the legacy backend and `sox_io.cpp` belongs to the new backend. So, the behavioral discrepancy between them is intentional. When I was working on `sox_io` backend, I did not think it makes sense to interpret `num_frames==0` for loading all the frames.

But this makes me think that we should change the parameter type to `num_frames: Optional[int]` instead of `num_frames: int = -1`.

**Comment by mthrok** [comment]
Closing the issue to consolidate the issue/discussion. Please comment on #903.
