### ISSUE TITLE
different library for loading audio files

### ISSUE THREAD

**Issue by dhpollack** [pytorch/audio#12]
I read that PyTorch doesn't want to add complex number tensor types.  A lot of audio processing requires fourier transforms, specifically into MEL spectrograms.  It would be nice to use a library that already handles a lot of these transformations in numpy.  The most popular one seems to be [librosa](http://librosa.github.io/), which uses numpy arrays for easy conversion to torch tensors.  

Is there any reason this library uses a cffi extension instead of a library such as librosa?

There are actually a lot more reasons to use librosa rather than the current solution, but it'd take too long to list them.  I wouldn't mind making a pull request to switch from the current libsox cffi way of doing things to the librosa/numpy way.

**Comment by soumith** [comment]
The reason that I started this library over librosa is because @jfsantos gave me feedback that there's no efficient way to load audio into a Tensor/ndarray in the python ecosystem. Almost all currently existing libraries (apparently) invoke a subprocess to `ffmpeg` or other equivalents and read/write through unix pipes, which is too heavy, when loading lots of small files in particular.

I'm happy to have this library shape up to be what everyone wants it to be.
In fact, I expected this lib to be something that just loads the files, and then folks would use scipy/librosa for actual pre-processing.

**Comment by dhpollack** [comment]
That makes a lot of sense.  My point is there seems to be a trade-off between efficiency and usability that is out of whack with this lib.  Using libsox directly makes the library more efficient, but because people get strange errors like #7 and #1 nobody really uses the library.

**Comment by dhpollack** [comment]
After I wrote my last comment I realized a lot of my gripes were due to errors that could easily be fixed by adding some checks in the load and save functions. Also, you are right, these functions load audio orders of magnitude faster than librosa. 

I'll go ahead and add some error checking to those functions instead of whining about it. :-)
