### ISSUE TITLE
Sox transforms work on CUDA tensors?

### ISSUE THREAD

**Issue by turian** [pytorch/audio#1452]
## ❓ Questions and Help

Do Sox transforms work on CUDA tensors? Or do they transfer the tensor to CPU and process there?

**Comment by mthrok** [comment]
Hi @turian 

If what you mean by "Sox transforms" is the filtering functions implemented in `torchaudio.functional`, (found under the category of [`filtering` in the official doc](https://pytorch.org/audio/stable/functional.html#filtering)), then they work with CUDA. You can pass Tensors transferred to CUDA and filtering functions will perform the operation in CUDA. (however this does not necessarily faster than CPU, because `torchaudio` does not have efficient CUDA-specific implementation)

If you mean functions under `torchaudio.sox_effects`, then no. They only support CPU and functions will raise an error.

Either way, functions in `torchaudio` do not automatically transfer Tensors across devices. It's up to users to move Tensor to an appropriate device.

**Comment by turian** [comment]
Thanks, my question was about `torchaudio.sox_effects`. Perhaps this could be added to the docs, just to be clear?

**Comment by mthrok** [comment]
Hi @turian 

Thanks for the suggestion. I agree. this can be better explained in the doc. 
I filed issue https://github.com/pytorch/audio/issues/1456. If no one picks up, I will work on it before the next release.

**Comment by turian** [comment]
Thank you

**Comment by rien333** [comment]
Any chance if sox effects ever working with CUDA, or is that unrealistic?

**Comment by mthrok** [comment]
Hi @rien333 

It's not impossible but it's a huge amount of work, and our engineering resource is very limited at the moment. So, yeah unfortunately it's unrealistic.

Right now, we have some filters re-implemented with PyTorch's generic Tensor operations. They are compatible with CUDA, but when tensors are moved to CUDA, operations become slower than CPU. Efficient filtering in CUDA requires implementations appropriate for CUDA style parallel computation.

**Comment by turian** [comment]
Thank you @mthrok for your wonderful work. Shinji speaks very highly of your project to me.

**Comment by mthrok** [comment]
@turian

Thanks for the such nice comments. I try to keep the bar high, but libraries cannot exist without users, so let's make something interesting together. :)
