### ISSUE TITLE
Voice Activity Detection

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#1468]
I'd love to hear from our users what is the impact of their favorite VAD algorithm on their model's performance at both training and inference (offline, online, streaming).
- Is there one we should add in torchaudio?
- Does anyone uses [webrtc's vad](https://github.com/wiseman/py-webrtcvad) implementation mentioned in [comment](https://github.com/pytorch/audio/issues/1348#issuecomment-817904097)?

We currently have in torchaudio
- [the example interactive ASR pipeline](https://github.com/pytorch/audio/blob/master/examples/interactive_asr/vad.py)
- [sox re-implementation in native pytorch](https://github.com/pytorch/audio/blob/master/torchaudio/functional/filtering.py#L1347)
- [apply_effects_tensor with VAD effect](https://github.com/pytorch/audio/blob/master/torchaudio/sox_effects/sox_effects.py#L55)

cc @mthrok @astaff

**Comment by PetrochukM** [comment]
Voice Activity Detection has been important for TTS and STT. It's useful for segmenting large datasets before training. I'd love a basic VAD implementation akin to:
https://maelfabien.github.io/project/Speech_proj/#pros-and-cons

`webrtc` didn't work for me because it didn't expose enough parameters for tunning. The default version of `webrtc` didn't work well for clean datasets... It tended to overcorrect for noise. It'd cut off unvoiced consonants because it thought they were noise... I tried all of the available settings in `py-webrtcvad` to correct for this. 

I don't think there is one perfect algorithm for VAD because you need to make all sorts of assumptions about noise and voice levels. So, I prefer a VAD which can be tuned by hand for different situations: no noise, minimal background noise, medium background noise, etc...  

The one currently in `torchaudio` didn't work for me because it is focused on audio trimming instead of detecting voice throughout the audio.

**Comment by vincentqb** [comment]
great response @PetrochukM, thanks a lot for the input :)

**Comment by vincentqb** [comment]
(quick note: some elements of [the algorithm you suggested](https://maelfabien.github.io/project/Speech_proj/#pros-and-cons) are also similar to one of the [pitch detection algorithm](https://github.com/pytorch/audio/blob/master/torchaudio/functional/functional.py#L975) we have)

**Comment by PetrochukM** [comment]
Oh. I didn't. Thanks for the tip! It looks pretty close to what I was describing :) 

Also, another issue that we had with VAD was memory. For some reason, [`scipy` doesn't support `memmap`](https://dsp.stackexchange.com/questions/73937/memory-efficient-filtering-with-scipy-signal-in-python). This made it particularly difficult to work with files longer than 1 hour. 

I actually tried to use the pitch detection algorithm in `torchaudio` but it was just too slow compared to other algorithms. I don't have too many details right now but it was much slower than something like loudness detection. I can give more details, in another thread, sometime later!

**Comment by vincentqb** [comment]
@PetrochukM, have you tried the kaldi voice activity detection? also mentioned in [pytorch forum](https://discuss.pytorch.org/t/kaldi-voice-activity-detection-vad/103001)

**Comment by PetrochukM** [comment]
Sorry, I can't be too helpful! I considered it but I decided against it during my research. I vaguely remember being overwhelmed by the complexity of it.

**Comment by vincentqb** [comment]
> I hope my POV helps!

Definitely, thank you :)
