### ISSUE TITLE
`Segmentation fault (core dumped)` err while applying `apply_effects_tensor()` 

### ISSUE THREAD

**Issue by mindaugo1** [pytorch/audio#1692]
## 🐛 Bug

While applying audio effects via `apply_effects_tensor()` function, an error `Segmentation fault (core dumped)` is raised.

## To Reproduce

To reproduce an error, run a script which iterates over an audio dataset and applies effects via `apply_effects_tensor()` function. The script can be found here: [segmentation_err.py](https://gist.github.com/mindaugo1/ffd9e0d1d7a84c1436cef94e2f619c73)
An error is raised randomly, and there is no specific pattern on which iteration we can expect it. It can be raised on 5 iteration as well as in 50.

## Expected behavior
Effects should be applied without raising an error.

## Environment

 - What commands did you used to install torchaudio: `conda install -c pytorch torchaudio`  
 - What does `torchaudio.__version__` print?  `0.9.0a0+33b2469`

```

 - PyTorch Version: `1.9.0`
 - OS (e.g., Linux): `Ubuntu 20.04.2 LTS`
 - How you installed PyTorch (`conda`, `pip`, source): `conda`
 - Python version: `Python 3.8.8`
 - CUDA/cuDNN version: `CUDA Version: 11.2`
 - GPU models and configuration: `GeForce RTX 2080, driver=nvidia latency=0`, `GeForce GTX 1070, driver=nvidia latency=0`

**Comment by mthrok** [comment]
Hi @mindaugo1 

Thanks for the report. I could reproduce the issue. I will look into this.

**Comment by mthrok** [comment]
Case 1.
```
[('gain', '-n', '7'), ('pitch', '-139'), ('speed', '1.08360'), ('rate', '8000'), ('pad', '0', '3'), ('trim', '0', '3')]
```

**Comment by mthrok** [comment]
It is reproducible on Colab as well.

https://colab.research.google.com/drive/16WIUNc-kLG3xQCe6wkk9WlkTtszdfpRO?usp=sharing

**Comment by mthrok** [comment]
The equivalent `sox` command line also segfaults.

```
% sox -V3 foo.wav foo2.wav  pitch -139 speed 1.08360 rate 8000
sox:      SoX v14.4.2
sox INFO formats: detected file format type `wav'
sox INFO wav: EXTENSIBLE
sox INFO tempo: quick_search=0 factor=1.0836 segment=82 search=14.6769 overlap=12.0006

Input File     : 'foo.wav'
Channels       : 1
Sample Rate    : 8000
Precision      : 32-bit
Duration       : 00:00:03.69 = 29531 samples ~ 276.853 CDDA sectors
File Size      : 118k
Bit Rate       : 256k
Sample Encoding: 32-bit Signed Integer PCM
Endian Type    : little
Reverse Nibbles: no
Reverse Bits   : no

sox INFO sox: Overwriting `foo2.wav'

Output File    : 'foo2.wav'
Channels       : 1
Sample Rate    : 8000
Precision      : 32-bit
Sample Encoding: 32-bit Signed Integer PCM
Endian Type    : little
Reverse Nibbles: no
Reverse Bits   : no
Comment        : 'Processed by SoX'

sox INFO sox: effects chain: input         8000Hz  1 channels
sox INFO sox: effects chain: pitch       7382.8Hz  1 channels
sox INFO sox: effects chain: speed         8000Hz  1 channels
sox INFO sox: effects chain: rate          8000Hz  1 channels
sox INFO sox: effects chain: output        8000Hz  1 channels
[1]    42816 segmentation fault  sox -V3 foo.wav foo2.wav pitch -139 speed 1.08360 rate 8000
```

**Comment by mthrok** [comment]
Hi @mindaugo1 

This looks like a bug in libsox. I tried the equivalent of `sox` commands with various installations (`brew`, `conda`, and the `sox` command from torchaudio build artifact) and all of them exhibited the segmentation fault.

My guess is that sampling rate is mistreated at `speed` and `rate` effect. (With `pitch -139 speed 1.08360`, the sample rate is around `8000.002`, which is very close to `8000` and `rate` effect is not handling something.)
(Although `pitch -165 speed 1.099999588 rate 8000` works. In this case, the intermediate sample rate is  `8000.003`.)

It is difficult for us to fix this issue coming from libsox. Once thing I can try is to update the libsox to the latest commit, hoping it is fixed somehow.

Meanwhile, what I recommend (based on my finding) is to restrict the value of `speed` so that the resulting sampling rate is not too close to 8000Hz. The problematic thing was that the string value of `speed` had 5 decimal points `1.08360` which made the resulting sampling rate very close but different `8000.002`. So limiting the decimal point to 3, i.e. `"speed", f"{speed:.3f}"` would not cause this.

The quick calculation says that, with pitch between -200 to 200, the sample rate right after the pitch is 7127.2Hz to 8979.69Hz with increment varying around 4 ~ 5 Hz. and the closest it gets is when `pitch -165 speed 1.100 rate 8000` -> `8000.003` and this seems to work.

**Comment by mindaugo1** [comment]
@mthrok Thank you for your insights. By changing `{speed:.5f}"` to `{speed:.3f}"f` solved an issue.
