### ISSUE TITLE
InverseMelScale does not work in inference mode

### ISSUE THREAD

**Issue by mthrok** [pytorch/audio#1902]
`InverseMelScale` uses SGD inside so it does not work when the global context is `no_grad` or `inference_mode`. Or even when `requires_grad=False` would make it fail. This gives bad UX for inference.

There are couple of possible workarounds
1. Clone Tensor with `requires_grad=True` inside of `InverseMelScale`
2. Use other method such as SVD. (there was some discussion https://github.com/pytorch/audio/pull/366)

```python
import torch
import torchaudio

trans = torchaudio.transforms.InverseMelScale(n_stft=10)

spec = torch.randn(128, 256, requires_grad=True)
trans(spec)  # pass
with torch.inference_mode():
    trans(spec)  # fail

spec = torch.randn(128, 256, requires_grad=False)
trans(spec)  # fail
with torch.inference_mode():
    trans(spec)  # fail
```

```
Traceback (most recent call last):
  File "foo.py", line 10, in <module>
    trans(spec)
  File "/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Development/torchaudio/torchaudio/transforms.py", line 472, in forward
    new_loss.backward()
  File "/miniconda3/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/miniconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

**Comment by spyroot** [comment]
Hi, @nateanl did you port nnls method?

**Comment by nateanl** [comment]
Hi @spyroot , not yet. I'll work on it after the 0.12 release. Stay tuned!

**Comment by spyroot** [comment]
Ratio of relative diff smaller than 1.000000e-01 is 7.614522473886609e-05
Ratio of relative diff smaller than 1.000000e-03 is 0.0
Ratio of relative diff smaller than 1.000000e-05 is 0.0
Ratio of relative diff smaller than 1.000000e-10 is 0.0
Ratio of relative diff padded than 1.000000e-01 is 7.145936251617968e-05
Ratio of relative diff padded than 1.000000e-03 is 0.0
Ratio of relative diff padded than 1.000000e-05 is 0.0
Ratio of relative diff padded than 1.000000e-10 is 0.0

Ratio of relative diff librosa than 1.000000e-01 is 2.3429299744748278e-06 <--- was my target
Ratio of relative diff librosa than 1.000000e-03 is 0.0
Ratio of relative diff librosa than 1.000000e-05 is 0.0
Ratio of relative diff librosa than 1.000000e-10 is 0.0


Ratio of relative diff my impl 1.000000e-01 is 0.0 < --- :) solved
Ratio of relative diff my impl 1.000000e-03 is 0.0
Ratio of relative diff my impl 1.000000e-05 is 0.0
Ratio of relative diff my impl 1.000000e-10 is 0.0

**Comment by nateanl** [comment]
Hi @spyroot, do you mean you already implemented the nnls method? Would you like to open a pull request for it? We can help review after the PR is created. Thanks!

**Comment by spyroot** [comment]
Yes, I used LBFGS and tested on GPU crazy fast and superb abs error with the original source. I'll do a pull request next week. But I had two fixes for two bugs in LBFGS, which I need to commit together.

I have one question about the current implementation. Torch does backward pass in InverseMelScale.
So if you do that in the training loop, it is a second backward pass.

So how is it intended to be used if you want to compute inverse in the training loop?

**Comment by spyroot** [comment]
@nateanl thank you very much.   The reason I asked about the second case.   Imagine we are working in none GAN settings. 
if you call a backward inside a loss function, that brake things a bit.

imagine a training pass. (pseudocodish)
   for batch in batches: 
       loss=compute_lose(x) -> if compute_lose does inverse and it has backward()
       self.scaler.scale(loss).backward()
       self.scaler.step(optimizer)
       self.scaler.update()


It is problematic. 

Yes, we probably can formulate it as GAN.   i.e, you do backward() on the main optimizer than 
then compute the Inverse.

Thinking a bit deeper. If Inverse computes a solution Ax=b and it is a Solution.
And we know that solution exists. 
( in this case, by the way, if  you find a solution, you don't need to deal with Complex)

Why is it because the solution is float, i.e, you can find a solution for complex, complex -> the output float.
Then you can technically compute Inverse inside  But, why.   Why would you want to do that?
We imagine you need that Inverse for loss computation.   But if you do have a solution
You don't need to minimize anything.

Do you see my point? For example, in my case. I have to do this. 
in compute_loss().  I am still trying to figure out the most efficient way to do this and avoid backward()

                with torch.no_grad():
                    x1 = self.dts_inverse(mel_padded)
                    x2 = self.dts_inverse(mel_out_post_net)

dts_inverse is my implementation.

**Comment by nateanl** [comment]
@spyroot I see. So in your implementation, `dts_inverse` doesn't require gradient optimization. This helps solve the issue that `InverseMelScale` can't work in inference mode. 

Regarding the usage in training, although we don't intend to optimize the `InverseMelScale`, the differentiability of the module is important. Take speech enhancement task as an example, some methods optimize the model based on waveforms instead of spectrograms. They indeed achieve some performance gain by doing that. In that case, we don't want the module is hard-coded as `with torch.no_grad()` because that breaks the chain of gradients.

**Comment by stonelazy** [comment]
> I found another solution in [librosa](https://librosa.org/doc/0.7.2/_modules/librosa/feature/inverse.html#mel_to_stft). in [`librosa.utils.nnls`](https://librosa.org/doc/0.7.2/_modules/librosa/util/_nnls.html#nnls) it uses np.linalg.lstsq which can be replaced by [`torch.lstsq`](https://pytorch.org/docs/stable/generated/torch.lstsq.html). So that we don't need to re-implement the SGD manually.

Just wanted to know whether this is implemented by any chance.

**Comment by 747929791** [comment]
Can this issue be solved by temporarily setting [<code>torch.enable_grad</code>](https://pytorch.org/docs/stable/generated/torch.enable_grad.html) at the call site or inside the function?

**Comment by nateanl** [comment]
> Can this issue be solved by temporarily setting [torch.enable_grad](https://pytorch.org/docs/stable/generated/torch.enable_grad.html) at the call site or inside the function?

`torch.enable_grad` works with `torch.no_grad`, but `torch.inference_mode` is more strict which doesn't record computation in the backward graph. Therefore the optimization inside `InverseMelScale` can't be run.

**Comment by mthrok** [comment]
Addresed via #3280
