### ISSUE TITLE
UserWarning: torchaudio C++ extension is not available

### ISSUE THREAD

**Issue by problemSolvingProgramming** [pytorch/audio#2155]
### 🐛 Describe the bug

Having just started learning Torchaudio, I got this error. I fixed the first part but even after some deep internet surfing, I can't find a fix. I use Windows 10.

https://pytorch.org/audio/stable/backend.html 

### Versions

version 1

**Comment by mthrok** [comment]
Hi @problemSolvingProgramming 

I cannot tell what you are referring by "the first part" or what you mean by "version 1".
That warning is issued when the installation of torchaudio does not have the extension module.
This happens, for example, when trying to use the source cloned via git, without building the extension module.
This is an expected behavior for older versions of torchaudio on Windows, but the rest of the features should work fine.
