### ISSUE TITLE
MFCC gives wrong sequence length

### ISSUE THREAD

**Issue by yzhang123** [pytorch/audio#249]
## To Reproduce

1. take input tensor of size `torch.Size([64, 276978])`
2. forward pass with 
```
torchaudio.transforms.MFCC(sample_rate=16000,  n_mfcc=40, dct_type=2, norm='ortho', log_mels=False)
```
3. you get `[64, 40, 1385]`

## Expected behavior

however i expect `[64, 40, 1732]`
since if i forward pass same input through
```
torchaudio.transforms.MelSpectrogram(sample_rate=16000, n_fft=512, win_length=320 \
                    hop_length=160, f_min=0.0, f_max=8000, pad=0, n_mels=64)
```
gives `[64, 40, 1732]`

**Comment by jamarshon** [comment]
```
waveform = torch.ones(64, 276978)

# torch.Size([64, 40, 1385])
torchaudio.transforms.MFCC(
	sample_rate=16000, n_mfcc=40, 
	dct_type=2, norm='ortho', 
	log_mels=False)(waveform).shape

# torch.Size([64, 64, 1732])
torchaudio.transforms.MelSpectrogram(
	sample_rate=16000, n_fft=512, 
	win_length=320, hop_length=160, 
	f_min=0.0, f_max=8000, pad=0, 
	n_mels=64)(waveform).shape
```

@yzhang123 Can you explain why this is incorrect?
https://pytorch.org/audio/transforms.html#torchaudio.transforms.MFCC
torch.Size([64, 40, 1385]) is (channel, n_mfcc, time)
You have 64 channels from the waveform, 40 n_mfcc because you pass in n_mfcc=40, and the time is a function of the length of your waveform, n_fft, and hop_length

https://pytorch.org/audio/transforms.html#torchaudio.transforms.MelSpectrogram
torch.Size([64, 64, 1732]) is (channel, n_mels, time)
You have 64 channels from the waveform, 64 n_mels because you pass in n_mels=64, and again the time is a function of the length of your waveform, n_fft, and hop_length

In the example that you posted above, n_fft and hop_length differ between the two transforms so ending up with different length is expected.

If you want the exact same dimensions for the two outputs, you need the 
 - input waveform to have the same number of channels (outputs first dimension)
 - n_mels==n_mfcc (outputs second dimension)
 - input waveform to have the same length, same n_fft and same hop_length (outputs third dimension)

Example:
```
waveform = torch.ones(64, 276978)
n_mfcc_or_n_mels = 20
n_fft = 500
hop_length = 121

# torch.Size([64, 20, 2290])
torchaudio.transforms.MFCC(
	sample_rate=16000, n_mfcc=n_mfcc_or_n_mels, 
	dct_type=2, norm='ortho', 
	log_mels=False, melkwargs={'hop_length': hop_length,
	'n_fft': n_fft})(waveform).shape

# torch.Size([64, 20, 2290])
torchaudio.transforms.MelSpectrogram(
	sample_rate=16000, n_fft=n_fft, 
	win_length=320, hop_length=hop_length, 
	f_min=0.0, f_max=8000, pad=0, 
	n_mels=n_mfcc_or_n_mels)(waveform).shape
```

**Comment by vincentqb** [comment]
Please feel free to re-open the issue if this does not address your issue.
