### ISSUE TITLE
PSD, MVDR are not found in torchaudio transforms/functional 

### ISSUE THREAD

**Issue by Kash2610** [pytorch/audio#2503]
### 📚 The doc issue

I tried accessing the multichannel transforms from torch audio but couldn't load them. Any updates?

**Comment by nateanl** [comment]
Hi @Kash2610, `PSD` and `MVDR` modules are under `torchaudio.transforms`. You can use them by initializing the module. For example:
```python
transform = torchaudio.transforms.PSD()
psd_matrix = transform(spectrum)
```
Could you print the versions of your PyTorch and torchaudio libraries? You can fetch them by
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Thanks.

**Comment by Kash2610** [comment]
Hi @nateanl thank you for your reply. So I have touchaudio 0.9.0 and torch 1.9.0+cuda11. I tried to get PSD from torch audio but the same error. the module has no attribute "PSD".  I even printed out all the attributes or functions for torchaudio functional but I could not see PSD or MVDR in the list.  Thanks for the script to get the versions.

**Comment by nateanl** [comment]
I see. It is expected since ``PSD`` and ``MVDR`` modules are added in [torchaudio 0.10](https://github.com/pytorch/audio/blob/release/0.10/torchaudio/transforms.py#L1606), thus you can't find it in [torchaudio 0.9.0](https://github.com/pytorch/audio/blob/release/0.9/torchaudio/transforms.py).

I recommend using the latest version of torchaudio. In the coming 0.12 release we have new beamforming modules (`SoudenMVDR`, `RTFMVDR`) under [`torchaudio.transforms`](https://pytorch.org/audio/0.12.0/transforms.html#multi-channel) and new beamforming methods (`psd`, `mvdr_weights_sounden`, etc) under [`torchaudio.functional`](https://pytorch.org/audio/0.12.0/functional.html#multi-channel). If you would like to have a try, you can use them by intsalling the **nightly** version of PyTorch and torchaudio via https://pytorch.org/get-started/locally/
Thanks!

**Comment by Kash2610** [comment]
Thanks. I will update it then. I did install it through pip3 but guess it did not install the latest one.
