### ISSUE TITLE
[docs] Function arguments in function signature are missing for many functions

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/audio#278]
https://pytorch.org/audio/functional.html

Many functions like `mu_law_encoding` are listed as `torchaudio.functional.mu_law_encoding()` with no arguments (unlike the `istft` function that has them in the signature). Arguments are still specified below in the Parameters section, but it is confusing.

**Comment by vincentqb** [comment]
The problem comes from the fact that those functions are decorated with `@torch.jit.script`. The forward looking solution is probably to remove the decorator (still test that they can be decorated). 

PS In the same vein, transforms should probably also be transferred from `torch.jit.ScriptModule` to `nn.Module`.

**Comment by mthrok** [comment]
Closing the issue as they look fine in the latest documentation. https://pytorch.org/audio/0.7/functional.html
