### ISSUE TITLE
reduce aliasing in downsampling

### ISSUE THREAD

**Issue by faroit** [pytorch/audio#30]
Currently the VCTK dataset loader does [implement](https://github.com/pytorch/audio/blob/master/torchaudio/datasets/vctk.py#L42) downsampling without low-pass filtering (=decimation). This results in severe aliasing artifacts and [should be avoided](https://en.wikipedia.org/wiki/Decimation_(signal_processing)). 

I would propose to add [resampy](https://github.com/bmcfee/resampy) as a dependency and include this in the base modules so that dataset loaders can utilize a high quality resampling. 

I can compile a PR if you like this proposal

**Comment by 0x00b1** [comment]
@faroit 👍 However, I’d say go even further and make librosa a dependency. What do you think?

**Comment by faroit** [comment]
I think it depends on what the future of torchaudio should be.
For many basic transforms like STFT it would be possible and favorable to implement them purely in pytorch so that users would benefit from a gpu speedup (See [https://github.com/keunwoochoi/kapre](kapre) from @keunwoochoi). But then, for many advanced operations or data augmentations, users would still use librosa or muda anyway and I don't think it makes sense to build a wrapper for librosa...

**Comment by vincentqb** [comment]
As you pointed out, we currently use sox within VCTK, though we are trying to reduce the dependency on sox. Similarly, we should avoid such large dependencies such as librosa if possible. In fact, we now have a `Resample`, see #134 and [release notes](https://github.com/pytorch/audio/releases), which we should leverage in this case.

I'm also linking pytorch/pytorch#24915 since we are also planning to decouple dataset loading from pre-processing.

**Comment by mthrok** [comment]
We have added bunch of quality control parameter to resampling, Kaiser window support, rolloff etc. One can perform resampling without sever degradation.

For the comparison with librosa, please refer to
https://pytorch.org/tutorials/beginner/audio_preprocessing_tutorial.html#resampling
