### ISSUE TITLE
Torchaudio and Sox disagree on audio duration of mp3 when using sox_io backend

### ISSUE THREAD

**Issue by rbracco** [pytorch/audio#3075]
### 🐛 Describe the bug

When loading certain audios in torchaudio, the number of samples (and hence duration) differs from what is output by sox (v14.4.2) and soxi, while using the sox_io backend to torchaudio. Torchaudio.load however does agree with ffmpeg, is torchaudio using ffmpeg or sox for backend decoding here? Any solutions for getting sox and torchaudio to agree on duration? 

**TorchAudio**
```
>>> torchaudio.backend.get_audio_backend()
'sox_io'
>>> y, sr = torchaudio.load('smash.mp3')
>>> y.shape
torch.Size([1, 13824])
```

**FFMpeg**
```
>>> ffmpeg -i smash.mp3

Duration: 00:00:00.86, start: 0.000000, bitrate: 24 kb/s
    Stream #0:0: Audio: mp3, 16000 Hz, mono, fltp, 24 kb/s

```

**Soxi**
```
>>> soxi smash.mp3

Input File     : 'smash.mp3'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:00.83 = 13248 samples ~ 62.1 CDDA sectors
File Size      : 2.59k
Bit Rate       : 25.0k
Sample Encoding: MPEG audio (layer I, II or III)
```

**Sox**
```
>>> sox smash.mp3 -n stat

Samples read:             13248
Length (seconds):      0.828000
Scaled by:         2147483647.0
Maximum amplitude:     0.762141
Minimum amplitude:    -0.353673
Midline amplitude:     0.204234
Mean    norm:          0.047697
Mean    amplitude:    -0.000218
RMS     amplitude:     0.100115
Maximum delta:         0.259187
Minimum delta:         0.000000
Mean    delta:         0.017760
RMS     delta:         0.029922
Rough   frequency:          761
Volume adjustment:        1.312
```

### Example Audio for Reproduction:
[Google Drive Link to Audio](https://drive.google.com/file/d/1yhmwXiq4ZG843rpXHkpHqH_VsLDVoRtn/view?usp=share_link)

### Possibly Related Issue
https://github.com/pytorch/audio/issues/329

### Versions

ububtu 20.04
sox 14.4.2
torch 1.13.1
torchaudio 0.13.1

**Comment by mthrok** [comment]
Hi @rbracco 

This is a bit complicated.

What we konw is that libsox and FFmpeg treat MP3 differently. https://github.com/pytorch/audio/issues/1500 has some description about the padding. We think that FFmpeg's behavior is the correct one because it prevents the grows/shrink of signal data when saving/loading the data. In v0.12, torchaudio switched to ffmpeg for loading mp3, which is the reason why it does not match with the bare `sox` command.

> Any solutions for getting sox and torchaudio to agree on duration?

At the moment, no. But we are making some changes to IO, which can resolve this. In the upcoming release, we are introducing a backend dispatcher so that one can specify IO backend per function call. https://github.com/pytorch/audio/issues/2950 In the release after that, we plan to change the way libsox is linked. libsox will be linked dynamically and we will ask users to install libsox. This way, the same mp3 decoder/encoder that `sox` command uses will be used by torchaudio.load with libsox backend.

**Comment by rbracco** [comment]
Thanks for the thorough explanation, I can work around it but just wanted to make sure it was on your radar. Glad to know a long-term solution is on the way.
