### ISSUE TITLE
What would be the alternative of torchaudio.transforms.DownmixMono()  module?

### ISSUE THREAD

**Issue by aiscientist** [pytorch/audio#363]
## ❓ Questions and Help

Hi, I am curious about **torchaudio.transforms.DownmixMono()** features which is not available in a current version of application.

What would be the reason this feature is disappeared? Or Is there a alternative module that makes stereo channels to mono channel?

Thanks

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by vincentqb** [comment]
As mentioned in the [release notes](https://github.com/pytorch/audio/releases), we removed DownmixMono since we can simply use `torch.mean` instead.

**Comment by thelou1s** [comment]
self.mixer = torchaudio.transforms.DownmixMono()

Hello, do you know how to use torch.mean instead of DownmixMono, in my code above? thx

**Comment by vincentqb** [comment]
If you have a `waveform` with shape `[2, 100]`, you can do 
```
waveform_mono = torch.mean(waveform, dim=0).unsqueeze(0)
```
and `waveform_mono` will have shape `[1, 100]`.

**Comment by cpuhrsch** [comment]
There even is a ["keepdim" keyword argument](https://pytorch.org/docs/master/tensors.html#torch.Tensor.mean) that folds the unsqueeze into mean.

**Comment by vincentqb** [comment]
Good point :)
```
waveform_mono = torch.mean(waveform, dim=0, keepdim=True)
```

**Comment by LukasNel** [comment]
I think you should add back this: this is completely unobvious, and probably has a few caveats that would be best captured by having it be a function in torchaudio, especially since it's a common action.

**Comment by set-soft** [comment]
Is this really correct? I mean: if you have two signals in antiphase, the result is 0, which I don't see as a good downmix ...

Asking it because I implemented exactly what is suggested here and the result was poor for the first music I tested, might be coincidence.

Asking about it to an LLM its says (can someone with good field experience can verify it?)

---
### The Problem with Simple Averaging

1.  **Phase Cancellation:** As you correctly pointed out, if parts of the left and right channels are perfectly out of phase (one is positive while the other is negative by the same amount), they will destructively interfere and cancel each other out when summed. A common example is "stereo widening" effects that work by manipulating phase. A simple mono sum can make these parts of the mix disappear entirely.

2.  **General Level Reduction:** Even with perfectly in-phase signals, the perceived loudness can change. In professional audio, when summing two correlated signals (like the L and R of a typical stereo mix), the resulting signal's peak level increases. A simple average (`(L+R)/2`) is done to prevent clipping, but this doesn't always map directly to perceived loudness (which is closer to RMS power). The standard practice often involves not just summing but also applying a gain adjustment.

### The Standard Solution: Pan Law and Gain Compensation

In Digital Audio Workstations (DAWs) and audio engineering, this is handled by a "pan law" or a standard downmix gain compensation. When you pan a signal from hard-left to the center, its level in both speakers changes according to a rule. The reverse is true for downmixing.

A common downmix formula that better preserves perceived loudness and avoids excessive phase cancellation issues is not just a simple average. A standard recommendation (e.g., by the ITU) is to sum the channels with a slight attenuation:

**Mono = 0.707 * Left + 0.707 * Right**

This is equivalent to: **Mono = (Left + Right) / sqrt(2)**

This is attenuating each channel by **-3 dB** before summing. This is a common "constant power" panning law. If the L and R signals are identical (perfectly correlated), the sum `L+R` results in a +6 dB increase in level. Dividing by 2 brings it back down by 6 dB to the original level. If they are completely uncorrelated (like two different instruments panned hard L/R), the sum results in a +3 dB increase. Dividing by `sqrt(2)` brings it back down by 3 dB.

Most real-world audio is somewhere in between, so the -3 dB attenuation is a good psychoacoustic compromise that generally sounds more natural and preserves loudness better than a simple average.
---

So a simple "mean" might be a bad idea ...

**Comment by faroit** [comment]
@set-soft Your assessment is correct, mean does mess up the phase sometimes and is often not the best mono downmix one could do. The "fixes" you posted are just changing the gains though, so the problem would still be there. What you could do is downmixing in the spectral domain.

**Comment by set-soft** [comment]
Hi @faroit, thanks for the idea, do you know about some code doing it with low distortion?

This is what I tried:

```python
# Copyright (c) 2025 Salvador E. Tropea
# Copyright (c) 2025 Instituto Nacional de Tecnología Industrial
# License: GPLv3
# Project: ComfyUI-AudioBatch
#
# Audio stereo to mono downmixer
# i/STFT code from Demucs (by Meta)
# Original code from Gemini 2.5 Pro
import torch
import logging


# --- Using Demucs robust STFT and iSTFT implementations ---
# These are excellent as they handle windowing, device fallbacks, and reshaping.

def spectro(x: torch.Tensor, n_fft: int, hop_length: int) -> torch.Tensor:
    """
    Computes the Short-Time Fourier Transform (STFT) of a tensor.
    Handles batching and MPS device fallbacks.
    """
    *other, length = x.shape
    x = x.reshape(-1, length)  # Flatten batch and channel dimensions

    # Handle MPS device which might not support STFT with all options
    is_mps = x.device.type == 'mps'
    original_device = x.device
    if is_mps:
        x = x.cpu()

    window = torch.hann_window(n_fft, device=x.device)

    z = torch.stft(
        x,
        n_fft=n_fft,
        hop_length=hop_length,
        win_length=n_fft,
        window=window,
        center=True,
        pad_mode='reflect',
        normalized=True,
        return_complex=True
    )

    if is_mps:
        z = z.to(original_device)  # Move result back to original device

    _, freqs, frames = z.shape
    return z.view(*other, freqs, frames)


def ispectro(z: torch.Tensor, hop_length: int, length: int) -> torch.Tensor:
    """
    Computes the Inverse Short-Time Fourier Transform (iSTFT) of a complex tensor.
    """
    *other, freqs, frames = z.shape
    n_fft = 2 * (freqs - 1)
    z = z.view(-1, freqs, frames)

    is_mps = z.device.type == 'mps'
    original_device = z.device
    if is_mps:
        z = z.cpu()

    window = torch.hann_window(n_fft, device=z.device)

    x = torch.istft(
        z,
        n_fft=n_fft,
        hop_length=hop_length,
        win_length=n_fft,
        window=window,
        center=True,
        normalized=True,
        length=length
    )

    if is_mps:
        x = x.to(original_device)

    _, out_length = x.shape
    return x.view(*other, out_length)


def spectral_downmix(
    waveform: torch.Tensor,  # (B, C, N) stereo or multi-channel
    n_fft: int = 2048,
    hop_length: int = 512
) -> torch.Tensor:  # Returns (B, 1, N) mono
    """
    Downmixes a stereo or multi-channel audio to mono in the spectral domain
    to avoid phase cancellation, using robust STFT/iSTFT functions.
    """
    if waveform.shape[1] <= 1:
        logging.debug("Input is already mono, skipping spectral downmix.")
        return waveform

    batch_size, num_channels, num_samples = waveform.shape

    # 1. Perform STFT on the multi-channel waveform
    # The spectro function handles reshaping (B,C,N) -> (B*C,N) if needed,
    # but passing it directly as (B,C,N) is also fine as it correctly reshapes.
    spectrogram_multi_ch = spectro(waveform, n_fft=n_fft, hop_length=hop_length)
    # Shape is (B, C, F, T_spec)

    # 2. Separate magnitude and phase
    magnitudes = spectrogram_multi_ch.abs()
    phases = spectrogram_multi_ch.angle()

    # 3. Average the magnitudes across channels
    avg_magnitude = torch.mean(magnitudes, dim=1)  # (B, F, T_spec)

    # 4. Use the phase from the first channel as the reference
    ref_phase = phases[:, 0, :, :]  # (B, F, T_spec)

    # 5. Reconstruct the new mono complex spectrogram
    mono_spectrogram_complex = torch.polar(avg_magnitude, ref_phase)

    # 6. Perform inverse STFT
    # ispectro expects (..., F, T_spec) and returns (..., N)
    # Our mono_spectrogram_complex is (B, F, T_spec), which is perfect.
    mono_waveform_time = ispectro(mono_spectrogram_complex, hop_length=hop_length, length=num_samples)

    # Reshape to (B, 1, N) for ComfyUI AUDIO standard
    return mono_waveform_time.unsqueeze(1)
```

So may be having *torchaudio.transforms.DownmixMono()* is not a bad idea after all ...
