### ISSUE TITLE
Torchaudio 2.1 Fails to Load and Save Audios with More than 16 Channels

### ISSUE THREAD

**Issue by mravanelli** [pytorch/audio#3659]
### 🐛 Describe the bug

Hi, I noticed this weird behavior and I would like to report:

```
# This works
signal = torch.rand(16, 16000)
torchaudio.save('signal_multichannel.wav', signal, 16000)

# This does not work
signal = torch.rand(17, 16000)
torchaudio.save('signal_multichannel.wav', signal, 16000)
```

### Versions

Versions of relevant libraries:
[pip3] flake8==3.7.9
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.4.0
[pip3] torch==2.1.0
[pip3] torchaudio==2.1.0
[pip3] torchinfo==1.8.0
[pip3] torchvision==0.16.0
[pip3] triton==2.1.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.5           py39h6c91a56_3  
[conda] numpy-base                1.21.5           py39ha15fc14_3  
[conda] numpydoc                  1.4.0            py39h06a4308_0  
[conda] torch                     2.1.0                    pypi_0    pypi
[conda] torchaudio                2.1.0                    pypi_0    pypi
[conda] torchinfo                 1.8.0                    pypi_0    pypi
[conda] torchvision               0.16.0                   pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

**Comment by mthrok** [comment]
Hi @mravanelli 

Thanks for the report. This is related to backend migration.
It seems that FFmpeg does not handle certain number of channels well, because FFmpeg considers channel_layout as first citizen and the number of channels as derived property of channel layout, and FFmpeg thinks that there is no good channel_layout defined for 17 channels.

Can you provide `backend="sox"` to these calls? It will fallback to the same old sox backend, and it should work.

**Comment by mravanelli** [comment]
Yes, with sox it works. It is something related to FFmpeg. It is not a big
issue though. I think it would be great to raise an error easier to
interpret when people are using the FFmpeg backend with more than 16
channels.

**Comment by jeonhuhuhu** [comment]
Could you please share the library version where the training was successful?

pip install **torch** **torchvision** **torchaudio** **pytorch-lightning** **sentencepiece**

We can't proceed with the training because it's not installed.

First, thank you.

pytorch == ?
torchaudio == ?
torchvision == ?
pytorch-lightning == ?
sentencepiece == ?
