### ISSUE TITLE
how support ffmpeg args rtmp_playpath 

### ISSUE THREAD

**Issue by hackerxiaobai** [pytorch/audio#3684]
### 🚀 The feature

ffmpeg args rtmp_playpath , StreamWriter support ?

### Motivation, pitch

ffmpeg args rtmp_playpath , StreamWriter support ?

**Comment by mthrok** [comment]
I don't think this is currently supported. For StreamReader, there is `option` argument for the constructor. However, StreamWriter does not have the equivalent one, this is because I don't know how to pass such option dict to the underlying implementation.

For StreamReader, the option is set when creating AVFormatContext with [`avformat_open_input`](https://ffmpeg.org/doxygen/5.0/group__lavf__decoding.html#gac05d61a2b492ae3985c658f34622c19d) function.

https://github.com/pytorch/audio/blob/c5b69336e951beac842aae09bca5cc62c114e018/src/libtorio/ffmpeg/stream_reader/stream_reader.cpp#L39

But for StreamWriter, AVFormatContext is created with [`avformat_alloc_output_context2`](https://ffmpeg.org/doxygen/5.0/avformat_8h.html#af5930942120e38a4766dc0bb9e4cae74), which does not have the equivalent option argument.

https://github.com/pytorch/audio/blob/c5b69336e951beac842aae09bca5cc62c114e018/src/libtorio/ffmpeg/stream_writer/stream_writer.cpp#L22-L30

Need to understand how `ffmpeg` CLI handles this.

**Comment by mthrok** [comment]
Hmm, looking at the implementation of [`avformat_open_input`](https://ffmpeg.org/doxygen/5.0/demux_8c_source.html#l00207), perhaps one can just do [av_opt_set_dict](https://ffmpeg.org/doxygen/5.0/group__avoptions.html#gaf1a88e8f152d7835f111b1ef8813fb2e)??

**Comment by mthrok** [comment]
Actually, this is already supported. Pass the "rtmp_playpath": "<some value>" to [`open`](https://pytorch.org/audio/2.1.0/generated/torchaudio.io.StreamWriter.html#open) method.
