### ISSUE TITLE
[Feature] RandomCrop for Audio

### ISSUE THREAD

**Issue by haideraltahan** [pytorch/audio#416]
## 🚀 Feature
Similar to RandomCrop in torchvision but implemented for audio.
 
## Motivation
Often we have a model with fixed input but the dataset has variable audio length. One approach to remedy this problem would be to randomly crop the audio to a fixed length. Thereby, allowing us to feed to our model. I would've used RandomCrop in torchvision, however, it only takes PIL Image instead of a Tensor. We need it done on audio across time only not changing the channel dimension of the audio.

## Pitch
The implementation is for audio given a tensor. We would return a randomly cropped segment of the audio given a requested audio length. Keeping the same number of channels. Alternatively, if the audio is shorter in length than the requested audio length, we would pad the audio across time.

## Additional context
This is my first contribution hence I was not aware that I needed to create an issue before PR (#403). I apologize for that 😕

**Comment by vincentqb** [comment]
Thanks for bringing this up! This may be relevant to pytorch/vision#1375 for torchvision to migrate away from PIL. Let's see if they have interest in having something like this. @fmassa 

We had removed deterministic pad and trim since they already existed in pytorch, see #160. This is slightly different since it also adds randomness.

Opening an issue is usually a good idea, since this allows you to get feedback before starting to work on code that may or may not be aligned with current needs :)

**Comment by haideraltahan** [comment]
> We had removed deterministic pad and trim since they already existed in pytorch, see #160.

Thank you, in #403 I have utilized the pytorch version of pad.

**Comment by vincentqb** [comment]
By the way, when loading an audio file, torchaudio support reading only the segment provided. This avoids having to read a whole audio file when only a segment is of interest.

**Comment by mthrok** [comment]
Closing the PR as
1. `torchvision`'s `RandomCrop` now accepts `torch.Tensor`
2. This needs formal specification, as many audio training has corresponding metadata, which also needs to be cropped in the same time steps.
