### ISSUE TITLE
[Feature] batch save audio util function

### ISSUE THREAD

**Issue by haideraltahan** [pytorch/audio#418]
## 🚀 Feature

Save a given batch of tensors into audio files.

## Motivation

For a util high-level function, it would be useful to have a function that can save sampled audio tensor from a model into an audio file(s). Similar to [torchvision](https://pytorch.org/docs/stable/torchvision/utils.html), save_image util function.

## Pitch

I often work with generative models that generate audio. Across my projects, I consistently find myself writing a function that takes in generated tensor(s) of audio data and writes them as a wave file. We could also make such that given a mini-batch tensor we produce a folder of wave files.

## Alternatives

Currently, users need to manually write those functions that convert the tensors of audio data into wave files.

**Comment by vincentqb** [comment]
Can you elaborate on how this differs from `torchaudio.save`? see [here](https://pytorch.org/audio/#torchaudio.save)

**Comment by haideraltahan** [comment]
I apologize, I was not aware of such a function. However, we could improve on it by incorporating batch Tensors into a folder.

**Comment by vincentqb** [comment]
This could be interesting to have. I will flag this as shared dataset functionality to discuss in the context of pytorch/pytorch#24915.

**Comment by haideraltahan** [comment]
Further, we could also have an option to save all batches in one audio file, going sequentially from first to the last batch.

**Comment by vincentqb** [comment]
I've discussed with @fmassa about the functionality from torchvision.

As you point out in the description, [`torchvision.save`](https://pytorch.org/docs/stable/torchvision/utils.html#torchvision.utils.save_image) has an option to save many images into a grid, which can be convenient to have with images. This type of API could be interesting to have for `torchaudio.save`. However, we'd need to decide first what this means.

The equivalent for audio segments would be to append audio signals one after the other -- a functionality that can be done easily with existing pytorch functions. It is not clear how often this would be used.

If the goal is to save many files through a for-loop without multiprocessing, torchaudio would not be offering performance improvements over a standard python loop. With multiprocessing, we would need to see cases that would clearly benefit before going ahead and implementing something here.

However, with or without multiprocessing, we still need to standardize the way a user would generate names for files, and it is not clear what is the most natural way of providing this. I do not recommend doing that for now since it is also not available in torchvision.
