### ISSUE TITLE
Floating point exception: 8

### ISSUE THREAD

**Issue by PetrochukM** [pytorch/audio#428]
## 🐛 Bug

I managed to crash Python using `torchaudio` with a zero tensor.

## To Reproduce

```python
import torch
import torchaudio

torchaudio.compliance.kaldi.resample_waveform(torch.randn(0, 34440), 24000 * 4, 24000)
```

```bash
Floating point exception: 8
```

**Comment by haideraltahan** [comment]
This should fix it: 

`torchaudio.compliance.kaldi.resample_waveform(torch.randn(1, 34440), 24000 * 4, 24000)`

[torch.randn()](https://pytorch.org/docs/stable/torch.html#torch.randn) expect the size of the random tensor as parameters, hence, 0 in the first dimension, would not work.

**Comment by PetrochukM** [comment]
@haideraltahan Yes. I know how to fix it as well; however, it's a bug that Python crashed that should never happen. There should be some reasonable stack trace.

**Comment by vincentqb** [comment]
What would you expect the output to be for such an empty tensor? e.g.
* We could raise an assertion error.
* We could return empty tensor with the expected length.

Would you be interested in offering a pull request for this?

**Comment by PetrochukM** [comment]
I think if I were to put more time into this issue, I'd probably investigate which of the tensor operations fails. Then, I'd submit an issue to PyTorch. That seems initially the right approach.

**Comment by haideraltahan** [comment]
@PetrochukM I will look more into it and see which op is responsible. 

@vincentqb Can we say that returning an empty tensor sounds for a more sensible approach given that randn generate one without an assertion?

**Comment by haideraltahan** [comment]
This problem is being generated from `torch.nn.functional.conv1d` function.

Can be tested using this line of code:
`torch.nn.functional.conv1d(torch.randn(1, 0, 34486), torch.randn(0, 1, 49), stride=4, groups=0)`
This only occurs when `groups=0`. Otherwise, it would return this error:
'Given groups=1, expected weight to be at least 1 at dimension 0, but got weight of size 0 1 49 instead'

**Comment by vincentqb** [comment]
Since `torch.nn.functional.conv1d` is producing an error, I would lean toward following their lead and also provide an error.

A simple assert protecting the function `resample_waveform` would work in the short term with a link to this PR. Could you also open an issue for `torch.nn.functional.conv1d`?

**Comment by mthrok** [comment]
This now raises error with reasonable description and Python does not crash. Closing the issue.

```
Traceback (most recent call last):
  File "bar.py", line 5, in <module>
    torchaudio.functional.resample(torch.randn(0, 34440), 24000 * 4, 24000)
  File "/fsx/users/moto/torchaudio/torchaudio/functional/functional.py", line 1445, in resample
    resampled = _apply_sinc_resample_kernel(waveform, orig_freq, new_freq, gcd, kernel, width)
  File "/fsx/users/moto/torchaudio/torchaudio/functional/functional.py", line 1394, in _apply_sinc_resample_kernel
    resampled = resampled.transpose(1, 2).reshape(num_wavs, -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous
```
