### ISSUE TITLE
Fix optional test with fairseq

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#476]
- [x] As seen [here](https://travis-ci.org/github/pytorch/audio/jobs/667465577?utm_medium=notification&utm_source=github_status), we need to bump the python version used in example test in travis to at least 3.6.
- [x] Fix test
- [x] ~~Disable test~~

[internal doc](https://fb.quip.com/TxAbAzyVBt7t)

**Comment by tomassosorio** [comment]
Looking at for example:
[pytorch text](https://github.com/pytorch/text/tree/master/examples/text_classification), we can see that this show with pytorch and torchtext how to build a text classification, however I do not see the point of this example in the scope of torchaudio since basically just uses the `fairseq`, which already have examples in its repository.

I think would be beneficial to do an example only using the functionalities from torchaudio and pytorch to do an audio classification with SpeechCommands for example. This way really showing what torchaudio is meant for and its utility.

**Comment by vincentqb** [comment]
Thanks for the feedback :) This example was a partnership, and was helpful during the hacktackon last summer.

I agree with you that it'd be nice to have reference pipelines for researchers that also showcase torchaudio's ability more specifically. What kind of example would you suggest with SpeechCommands?

**Comment by tomassosorio** [comment]
Currently, tensorflow has a [tutorial](https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/audio_recognition.md), maybe would be better to use yesno dataset and create a simple classification, as a beginner tutorial, and then for an intermediary tutorial a simple ASR example, using pytorch implemented CTC and SpeechCommands.

**Comment by vincentqb** [comment]
@tomassosorio -- We would indeed welcome new tutorials that uses pytorch, torchaudio, and freely available datasets :) We could add it [here](https://pytorch.org/tutorials/) in https://github.com/pytorch/tutorials. Is that of interest to you?

**Comment by tomassosorio** [comment]
Absolutely, I will start working on that!

**Comment by vincentqb** [comment]
Awesome! you can open a pull request https://github.com/pytorch/tutorials and ping me on it :)

**Comment by vincentqb** [comment]
btw, feel free to open an issue over [there](https://github.com/vincentqb/audio-tutorial/blob/master/PipelineTrain.ipynb) to discuss how we should turn this into a reference implementation

**Comment by vincentqb** [comment]
This test is no longer ran as part of CircleCI.
