### ISSUE TITLE
ImportError when using pytorch compiled from the master branch with CUDA 10

### ISSUE THREAD

**Issue by kureta** [pytorch/audio#68]
I have compiled pytorch from the master branch using Python 3.7.1 and CUDA 10. Everything except pytorch-audio works. I receive this error when trying to import.

```
~/.pyenv/versions/3.7.1/envs/pytorch-venv/lib/python3.7/site-packages/torchaudio/__init__.py in <module>
      2 
      3 import torch
----> 4 import _torch_sox
      5 
      6 from torchaudio import transforms

ImportError: /home/kureta/.pyenv/versions/3.7.1/envs/pytorch-venv/lib/python3.7/site-packages/_torch_sox.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at18SparseCUDATensorIdEv
```

I can provide additional information if necessary.

**Comment by mvankeirsbilck** [comment]
I have the same issue (Python 3.6, PyTorch 0.4.1, CUDA 10.0, Ubuntu 16.04)

**Comment by pltrdy** [comment]
FYI I has similar issue, I solved it by updating `torchaudio` from the repo (i.e. cloning and `python setup.py install`).

Update from pip (`pip install --upgrade torchaudio`) was unsuccessful.

**Comment by kureta** [comment]
@pltrdy I was already doing something similar (building `.whl` file from source and installing that.). Tried your way, unfortunately didn't change anything.

**Comment by dhpollack** [comment]
@kureta @pltrdy are you guys still having problems with this?

**Comment by pltrdy** [comment]
@dhpollack the fix (see my last commit) did it for me.

**Comment by cpuhrsch** [comment]
@kureta - Is this issue still current? Based on the recent comments it appears resolved. I'm going to close this for now, but please feel encouraged to reopen it, if it's indeed not yet resolved.

**Comment by jmlemercier** [comment]
I have the same issue here: 

Was working on Ubuntu 18.04, `torchaudio =0.4.0` and `torch = 1.4.1`. Solved the problem by downgrading to  `torchaudio =0.3.1` and `torch = 1.3.0`.

However, when working on CentOS 7 (Core), I had the same issue with  `torchaudio =0.4.0` and `torch = 1.4.1` , so I tried to downgrade to  `torchaudio =0.3.1` and `torch = 1.3.0` as well, but that didn't solve anything. I tried different downgrades but still no luck. I read what was stated in [3](https://github.com/jinserk/pytorch-asr/issues/3) but I am not able to fix a build from source as I am not admin on the session. I also tried with `pipenv` as stated in the same issue, but there are conflicts between `pip` and `miniconda` environments, which I am not able to resolve as well because I am not admin...

Would appreciate a little help (not based on source fixes because I would not be able to implement them), thanks in advance !
