### ISSUE TITLE
Linting and formatting

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#856]
Thoughts on running `black` and `isort` on all files within torchaudio? I am suggesting we do so manually (and not automatically through a post-commit hook). 

* (+) contributors can simply run `black`/`isort` to ensure the formatting is standardized.  
* (-) git blame will show most files modified by the same PR (assuming the change is done in one PR)
* (+) contributors were already correcting lint/formatting as part of unrelated work, and doing this may reduce the occurrences (as noticed by both @mthrok and myself).

Thoughts @cpuhrsch @mthrok?

**Comment by mthrok** [comment]
I do not think there is an automatic way to perform formatting/linting as commit hook has to be installed manually by each user.
Also I found commit hook not helpful, because it prevents from pushing WIP, which I have no intention to format.

If you want an automatic way, you need a pusher job that does formatting and commit to master branch.

**Comment by vincentqb** [comment]
As I mention in the description, I did not mean "automatic" in the sense of post-hook commits, and I would not want that. :) I meant "automatic" in the sense of encouraging people to use black when they want. This is not possible right now just because of all the side effects that would happen.

That being said, we do check for flake8, so that is probably enough for my taste :)

**Comment by vincentqb** [comment]
I'm happy enough for now with enforcing flake8. Let's keep it as it is then :) I'm closing the issue, but feel free to re-open if you'd actually like to use black/etc applied to all files.

**Comment by vincentqb** [comment]
cc #854
