### ISSUE TITLE
How to index subsegments of audio tensor based on time

### ISSUE THREAD

**Issue by jiwidi** [pytorch/audio#879]
## How to select a subsegment from a tensor

Hello!

This may be a very noobie question but I can't get to solve it on my own. 

Lets say I want to select the first 10 seconds of an audio sample that I have loaded into a torch tensor with torchaudio, how should I determine the indexes of the tensor that correspond to the 10sec sample?

I have done some playing with audio files with different sample rate and if I were to save a subset of the tensor to audio `.wav` the same index `[:, :600000]` (600000 elements of all channels) doesn't return.

So if I select the subset `[:, :600000]` of a waveform tensor with shape `torch.Size([1, 21091521])` and sample rate `16000` I will get the first ~38 seconds.

While If I select the subset `[:, :600000]` of a waveform tensor with shape `torch.Size([2, 5385600])
` and sample rate `44100` I will get the first ~14seconds.

I suspect this is basic audio theory and how is stored in different channels and how sample rate affects but I haven't been able to find information about it.

Based on the channels and sample rate of a tensor, can I select a subset of seconds of this one? If so, how can I?

Thanks

**Comment by mthrok** [comment]
Hi @jiwidi 

> Lets say I want to select the first 10 seconds of an audio sample that I have loaded into a torch tensor with torchaudio, how should I determine the indexes of the tensor that correspond to the 10sec sample?

Sample rate represents the number of samples per second per channel. So you can simply multiply the duration you want in second and sample rate. `int(sample_rate * duration)`, (btw this is also called `frame` in the context where they do not want to consider the number of channels). 

For example if you want to get 10 seconds of audio data, with 44.1k [Hz], `tensor[:, :10 * 44100]` will get the first 10 seconds of audio data. This slicing operation should be no-op because there should be no memory copy.

> So if I select the subset `[:, :600000]` of a waveform tensor with shape `torch.Size([1, 21091521])` and sample rate 16000 I will get the first ~38 seconds.
> 
> While If I select the subset `[:, :600000]` of a waveform tensor with shape `torch.Size([2, 5385600])` and sample rate 44100 I will get the first ~14seconds.

In the first case, `600000 / 16000 = 37.5` so you get the first 38 seconds.
In the later case, `600000 / 44100 ~= 13.60` so you get the first 14 seconds.

> I have done some playing with audio files with different sample rate and if I were to save a subset of the tensor to audio .wav the same index `[:, :600000]` (600000 elements of all channels) doesn't return.

Now for the saving part, the speed of this operation should be mostly governed by the speed of disk I/O, and the time it takes to save audio is mostly proportional to the number of samples saved.

We have unit tests to ensure that our save function can handle large files. For `.wav` format, we test 16k [Hz], 2 channel, 2 hour audio, which has 115200000 samples per channel.

https://github.com/pytorch/audio/blob/c692fe99ac353f0e2fc7b5ad7162f037a70a35fe/test/torchaudio_unittest/sox_io_backend/save_test.py#L216-L224

You can try this with the following command

`pytest test/torchaudio_unittest/sox_io_backend/save_test.py -k wav_large --durations 0`

In my environment, it takes 11 seconds.

A similar (not exactly equivalent) operation using `sox` command is

`time sox -V3 --bits 16 --rate 16000 --null --channels 2 foo.wav synth 7200 sine 300`

This one returns 13 seconds.

These two command should return within similar time.

With that being said, 

> (600000 elements of all channels) doesn't return.

This seems suspicious. How long did you wait?

**Comment by jiwidi** [comment]
> This seems suspicious. How long did you wait?

That was just a miswriting of me, I didn't end the sentence that was supposed to be:  (600000 elements of all channels) doesn't return the same length in different audios with different sample rate

> Sample rate represents the number of samples per second per channel. So you can simply multiply the duration you want in second and sample rate. int(sample_rate * duration), (btw this is also called frame in the context where they do not want to consider the number of channels, and in this context, number of samples represents the number of samples across channels. So be aware of the fact that sometimes it can be confusing.).
For example if you want to get 10 seconds of audio data, with 44.1k [Hz], tensor[:, :10 * 44100] will do. This slicing operation should be no-op because there should be no memory copy.

This made it very clear to me thanks! You have been very helpful for all my issues lately :) 

Great explanation with how the I/O works as well.

**Comment by mthrok** [comment]
> > This seems suspicious. How long did you wait?
> 
> That was just a miswriting of me, I didn't end the sentence that was supposed to be: (600000 elements of all channels) doesn't return the same length in different audios with different sample rate

Does the original tensor contain more than 600000 elements?
Slicing operation works similar way as Python list, so it does not fail even when there is not enough elements.

**Comment by jiwidi** [comment]
> > > This seems suspicious. How long did you wait?
> > 
> > 
> > That was just a miswriting of me, I didn't end the sentence that was supposed to be: (600000 elements of all channels) doesn't return the same length in different audios with different sample rate
> 
> Does the original tensor contain more than 600000 elements?
> Slicing operation works similar way as Python list, so it does not fail even when there is not enough elements.

Yes, but both tensors had different sample rate so once converted to wav again didnt had same duration. But I have it clear now why this happens thanks to you
