### ISSUE TITLE
InverseSpectrogram transform

### ISSUE THREAD

**Issue by dvisockas** [pytorch/audio#942]
## 🚀 Feature
I'd like to propose adding of `InverseSpectrogram` transform to `torchaudio`

## Motivation
`istft` is already present in `torchaudio.functional` and if users want to build a cepstrum, they have to wrap the functional method into a torch module themselves.

## Pitch

Adding a wrapper for `functinal.istft`, similar to how `Spectrogram` transform wraps `F.spectrogram`

## Additional context

This thought arose from the fact that I was thinking about quick ways to implement various non-mel scale cepstral coefficients in pytorch (LFCC, CQCC, LPCC, BFCC, etc). Implementing all the various filterbanks seemed like it would overload the library. Adding the transform would alleviate the complexity needed to extract various cepstral coefficients.

**Comment by mthrok** [comment]
Hi @dvisockas 

Thanks for the proposal. Could you help me understand your proposal? The proposal is about Transform of Inverse of Spectrogram and which uses `istft`. Is that correct? I am asking this because `istft` was moved to PyTorch core and the one in `torchaudio` has been removed in master branch.

I think this is a good addition. Having a set of functionalities that can achieve roundtrip between time dimension and frequency dimension.

**Comment by dvisockas** [comment]
Precisely that. Basically a transform that wraps `torch.istft`. 

The ability to make an easy roundrip between time and frequency is the main thing why I am proposing this.

**Comment by vincentqb** [comment]
Thanks for the idea :) Can you explain how the algorithm differ from [Griffin-Lim](https://github.com/pytorch/audio/blob/master/torchaudio/functional.py#L102)?

**Comment by dvisockas** [comment]
Griffin-Lim takes a magnitude-only spectrogram and tries to recover the phase. `istft` takes both magnitude and phase tensor as an input. If you want to go into the frequency domain without discarding the phase you can pass `power=None` to the `Spectrogram` transform and you will get a magnitude-phase tensor. If you then do some transforms and want to go back to the time domain, you could pass only the magnitude part to the `Griffin-Lim`, but the phase would have to be reconstructed which is both slower and less accurate.

**Comment by vincentqb** [comment]
Good point :) Yes, that sounds like a good addition.

To test, how close are the original waveform and the reconstructed waveform? Since stft and istft are close, I would expect Spectrogram and InverseSpectrogram to be close. Is that correct? Otherwise, do you have a reference to match? I don't see it in librosa.

**Comment by dvisockas** [comment]
You're correct that they should be close. The question is how close. Will open a PR an we can see there how close they are.
