### ISSUE TITLE
Add noisered and ladspa in sox_effects

### ISSUE THREAD

**Issue by vincentqb** [pytorch/audio#988]
noisered and ladspa from [here](http://sox.sourceforge.net/sox.html) are not listed as an effect. Not picked up due to its interface?

```python
>>> from torchaudio.sox_effects.sox_effects import effect_names
>>> torchaudio.__version__
'0.7.0a0+ac17b64'
>>> effect_names()
['allpass', 'band', 'bandpass', 'bandreject', 'bass', 'bend', 'biquad', 'chorus', 'channels', 'compand', 'contrast', 'dcshift', 'deemph', 'delay', 'dither', 'divide', 'downsample', 'earwax', 'echo', 'echos', 'equalizer', 'fade', 'fir', 'firfit', 'flanger', 'gain', 'highpass', 'hilbert', 'loudness', 'lowpass', 'mcompand', 'norm', 'oops', 'overdrive', 'pad', 'phaser', 'pitch', 'rate', 'remix', 'repeat', 'reverb', 'reverse', 'riaa', 'silence', 'sinc', 'speed', 'stat', 'stats', 'stretch', 'swap', 'synth', 'tempo', 'treble', 'tremolo', 'trim', 'upsample', 'vad', 'vol']
>>> 'noisered' in effect_names()
False
```

It affects facebookresearch/WavAugment#16.

**Comment by mthrok** [comment]
The effects that are not tensor manipulation are explicitly not supported. We do not plan to support them.
`ladspa` is not explicitly excluded but probably the plugin is not available on your system.

https://github.com/pytorch/audio/blob/0e1d814b76725f50b76d938b474b616a15009b45/torchaudio/csrc/sox_utils.h#L50-L51

**Comment by rien333** [comment]
> ladspa is not explicitly excluded but probably the plugin is not available on your system.

I can use ladspa effects just fine when I manually call my `sox` binary, and I have all the required libraries installed to build `sox`  with ladspa support (AFAIK). 

Still, I get the following error whenever I apply a `ladspa` effect:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
...
    o, _ = torchaudio.sox_effects.apply_effects_tensor(
  File "/usr/lib/python3.9/site-packages/torchaudio/sox_effects/sox_effects.py", line 152, in apply_effects_tensor
    return torch.ops.torchaudio.sox_effects_apply_effects_tensor(
RuntimeError: Unsupported effect: ladspa vocoder
```

I also modified `audio/third_party/sox/CMakeLists.txt` such that ladspa support is explicitly included:

```diff
diff --git a/audio/third_party/sox/CMakeLists.txt b/audio/third_party/sox/CMakeLists.txt
index a7f2989..7ac0ec5 100644
--- a/audio/third_party/sox/CMakeLists.txt
+++ b/audio/third_party/sox/CMakeLists.txt
@@ -160,12 +160,12 @@ set(SOX_OPTIONS
   --with-mad
   --with-oggvorbis
   --with-opus
+  --with-ladspa
   --without-alsa
   --without-ao
   --without-coreaudio
   --without-oss
   --without-id3tag
-  --without-ladspa
   --without-magic
   --without-png
   --without-pulseaudio
```

 
@mthrok So is ladspa support out of the question, have I done something wrong, or does ladspa support require some special handling within the torchaudio implementation?

---
**system info**

```console
> ls $LADSPA_PATH
amp.so                 noise.so              ZamCompX2-ladspa.so     ZamGEQ31-ladspa.so
delay.so               sine.so               ZamDelay-ladspa.so      ZamGrains-ladspa.so
filter.so              vocoder.so            ZamDynamicEQ-ladspa.so  ZamPhono-ladspa.so
ladspa-rubberband.cat  ZamAutoSat-ladspa.so  ZamEQ2-ladspa.so        ZamTube-ladspa.so
ladspa-rubberband.so   ZaMaximX2-ladspa.so   ZamGate-ladspa.so       ZaMultiComp-ladspa.so
lsp-plugins-ladspa.so  ZamComp-ladspa.so     ZamGateX2-ladspa.so     ZaMultiCompX2-ladspa.so
> python
>>> import torchaudio
>>> torchaudio.__version__
'0.9.0a0+33b2469'
```

**Comment by rien333** [comment]
To somewhat answer my own question, it seems that sox with ladspa can only be build without `--disable-shared` (at least according to [this discussion](https://sourceforge.net/p/sox/mailman/sox-users/thread/20170710194108.GA15244%40whir/))

**Comment by mthrok** [comment]
Hi @rien333 

The build process has been changed since the time of above discussion, and `ladspa` is indeed explicitly disabled. This is because now we only support static build of `libsox` and because of an issue with in-memory decoding (for file-like object support) and many binary distribution of `libsox` provided by package manager has the issue. The issue with in-memory decoding has been patched on the latest dev version but there is no release that includes the patch.

I did not know much about `ladspa`, but according to your finding, the possible way to support is,
1. install the latest `libsox` with dynamic linking and `ladspa` support (if file-like object support matters, otherwise you can use the version from your system's package manager)
2. change the way `torchaudio` is built so that it links to the `libsox` from step 1.

Step 2. is not straightforward for us because we do not know how many different environments we need to support, and this makes the build process prune to configuration errors. If you would like to try, you can look at the previous version of [`CMakeLists.txt`](https://github.com/pytorch/audio/blob/2c8aad97fc8d7647ee8b2df2de9312cce0355ef6/third_party/CMakeLists.txt#L8-L18). You need to make sure that the version of `libsox` you want to use shows up first in the search path.

**Comment by rien333** [comment]
@mthrok Thanks for your quick and detailed reply! Following your instructions, I was able to add ladspa support.
